### ISSUE TITLE
Incompatible with alacritty

### ISSUE THREAD

**Issue by hitchho** [w3f/unbounded#9]
I am working on a new terminal centric operating system UI and wanting to use Unbounded for it. Anyhow it seems that it is not compatible in its current form with Alacritty. Rofi with .rasi files seems to be functioning correctly, but spacing tends to be incorrect in alacritty.

```
font:
  # The normal (roman) font face to use.
  normal:
    family: "Unbounded"
    style: Regular

  # The bold font face
  bold:
    family: "Unbounded"
    style: Bold

  size: 12.0

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
```
